name: 获取最新version
on:
  # 当master分支提交时
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */6 * * *'
  push: #推送version，开始编译
    branches:
      - main
    paths:
      - '.github/build/version'
jobs:
  checkversion:
    name: 检查是否有版本更新
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      
      - name: 对比检查版本号
        run: |
          j=1
          for i in {1..1060}
          do
            TAG=$(cat ".github/build/version" | head -1 | tr -d [:space:])
            wget --tries=10 https://raw.githubusercontent.com/XTLS/Xray-core/main/core/core.go
            VERSION=$(grep version ./core.go| head -n 1| cut -d = -f2| tr -d \"' ')
            if [ $TAG != v$VERSION ]
              then
              echo "找到更新！，更新版本为" v$VERSION "，即将写入version文件！"
              sed -i '/v/ s/'$TAG'/v'$VERSION'/' .github/build/version
              rm ./core.go
              sleep 2m
              break
            fi
            rm ./core.go
            if [$j == 10 ]
            then
            echo "第" $i "次查询结果，共1060次"
            $j=0
            fi
            j=$(expr $j + 1)
            sleep 20s
          done
          echo "TAG=v$VERSION" >> $GITHUB_ENV
      - name: Pull Changes
        uses: actions-go/push@master
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: ${{ env.TAG }}
          remote: origin
          author-name: github-actions
          author-email: github-actions@users.noreply.github.com
        

          

